
ALTER TABLE videos ADD COLUMN is_reel BOOLEAN DEFAULT 0;

CREATE TABLE IF NOT EXISTS reels (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    video_id INTEGER NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    caption TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0
);
