CREATE TABLE IF NOT EXISTS sochee (
 id INTEGER PRIMARY KEY REFERENCES content_blocks(id) ON DELETE CASCADE,
 single BOOLEAN NOT NULL,
 comments INTEGER DEFAULT 0,
 likes INTEGER DEFAULT 0,
 caption TEXT NOT NULL, 
 hashtag INTEGER NOT NULL,
 location TEXT NOT NULL DEFAULT '',
 has_link BOOLEAN NOT NULL
);
