name: Deploy DB Admin Interface

on:
  push:
    branches:
      - main
    paths:
      - 'db-admin/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy-db-admin:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy DB Admin Interface
      env:
        PRIVATE_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        VM_USER: ${{ secrets.VM_USER }}
        VM_IP: ${{ secrets.VM_IP }}
        SERVICE_FILE: |
          [Unit]
          Description=SQLite Database Admin Interface
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/db_admin
          WorkingDirectory=/usr/local/bin
          Restart=always
          RestartSec=5s
          User=root
          Group=root

          [Install]
          WantedBy=multi-user.target
      run: |
        # Setup SSH
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan $VM_IP >> ~/.ssh/known_hosts
        
        # Create required directory on VM if it doesn't exist
        ssh -i ~/.ssh/id_rsa $VM_USER@$VM_IP '
          sudo mkdir -p /usr/local/bin
          sudo mkdir -p /etc/systemd/system
        '
        
        # Copy the admin interface files
        scp -i ~/.ssh/id_rsa db-admin/db_admin.cpp $VM_USER@$VM_IP:/tmp/
        scp -i ~/.ssh/id_rsa db-admin/build_db_admin.sh $VM_USER@$VM_IP:/tmp/
        
        # Create service file locally and copy it
        echo "$SERVICE_FILE" > /tmp/db-admin.service
        scp -i ~/.ssh/id_rsa /tmp/db-admin.service $VM_USER@$VM_IP:/tmp/
        
        # Compile and install on VM
        ssh -i ~/.ssh/id_rsa $VM_USER@$VM_IP '
          # Install required dependencies
          sudo apt-get update
          sudo apt-get install -y g++ libsqlite3-dev
          
          # Move service file to system directory
          sudo mv /tmp/db-admin.service /etc/systemd/system/
          
          # Compile the application
          sudo g++ -std=c++17 -o /usr/local/bin/db_admin /tmp/db_admin.cpp -lsqlite3
          
          # Set proper permissions
          sudo chmod +x /usr/local/bin/db_admin
          
          # Reload systemd and restart service
          sudo systemctl daemon-reload
          sudo systemctl enable db-admin
          sudo systemctl restart db-admin
          
          # Verify service is running
          sudo systemctl status db-admin --no-pager
        '
        
        echo "Database admin interface deployed successfully!"
        echo "Access via: ssh -L 8888:localhost:8888 $VM_USER@$VM_IP"
